### GEOMETRY
/Geometry/PetBoxFBK/visibility true
/Geometry/PetBoxFBK/pressure 1.26 bar

/Geometry/PetBoxFBK/tile_vis true
/Geometry/PetBoxFBK/tile_refl 0.

/Geometry/PetBoxFBK/sipm_cells false

### GENERATOR
/Generator/IonGenerator/region SOURCE
/Generator/IonGenerator/atomic_number 11
/Generator/IonGenerator/mass_number 22
#/Generator/SingleParticle/particle geantino
#/Generator/SingleParticle/min_energy 1  eV
#/Generator/SingleParticle/max_energy 1 keV
#/Generator/SingleParticle/region CENTER
#/Generator/SingleParticle/momentum 0 0 -1

/Actions/PetSensorsEventAction/min_charge 50

### PHYSICS
#/process/optical/processActivation Scintillation true
#/process/optical/processActivation Cerenkov      true

### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 1

/process/em/verbose 0

/nexus/random_seed 132323

### OUTPUT FILE
/petalosim/persistency/sipm_cells false
/petalosim/persistency/save_tot_charge true

/petalosim/persistency/start_id 0
/petalosim/persistency/output_file petbox_fbk

